# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 844f0974be2c3034ed957f299d3935e12a7fa7d3e265130f72058f7a0d526c228e1247775321164c94a0879d7fec371f2e4c266f9b76bf58b80c925a4e7c567a

test:
  secret_key_base: 21119829b0681aed15822a60837e43b4e469a186b1a49b3f6beb94d9eaefdc313ecfcddd8efc7b70b5cad8f38f2e556f52edbbf94c11fa55ea4c7905fae4f429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
